### ISSUE TITLE
Installation Documentation - missing install of python cli beam-sdk

### ISSUE THREAD

**Issue by evelynmitchell** [slai-labs/get-beam#102]
The install documentation has a curl command to install beam, which is also used to update beam. (https://docs.beam.cloud/getting-started/installation)

The Mac/Linux and Windows instructions include only that curl command to install, and does not include the instructions to install the python cli:
```
python3 -m pip install --upgrade beam-sdk
```
The uninstall instructions do mention the beam-sdk, so the install instructions were just missed.

To replicate:
```
curl https://raw.githubusercontent.com/slai-labs/get-beam/main/get-beam.sh -sSfL | sh
python> import  beam
```
```
ModuleNotFoundError: No module named 'beam'
```
To verify the fix:
```
curl https://raw.githubusercontent.com/slai-labs/get-beam/main/get-beam.sh -sSfL | sh
python3 -m pip install --upgrade beam-sdk
python
python> import  beam
```

**Comment by mernit** [comment]
Hi @evelynmitchell -- thank you for opening this issue. Installation of the CLI will automatically install the Python SDK as well, so I am going to close this issue.
