### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by psmoros** [slai-labs/get-beam#104]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@hainguyen0207) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by hainguyen0207** [comment]
Hello.

Thank you for responding.

I don't know how to create SECURITY.md file.

I wrote the report on the Huntr platform.

https://huntr.com/bounties/5b9702e9-caa6-42c5-8cbb-f2f6caa2e796

Can you access it?

Thank you very much.

Vào Th 4, 15 thg 5, 2024 vào lúc 10:57 Pavlos ***@***.***>
đã viết:

**Comment by hainguyen0207** [comment]
Hello mernit.
Thank you for responding.
Can you let me know if the problem I reported is valid?

Thank you very much.
Best regards,
hainguyen0207
