### ISSUE TITLE
[docs] There is a typo in the docs

### ISSUE THREAD

**Issue by szepeviktor** [slai-labs/get-beam#110]
https://docs.beam.cloud/v2/getting-started/quickstart#remove-vs-local-environment
"remote", not "remove"

**Comment by mernit** [comment]
Hey @szepeviktor good catch! Thanks for opening the issue. This should be fixed now.

**Comment by szepeviktor** [comment]
@mernit Glad to contribute.

BTW Pages end with `</html></body></html>`

**Comment by mernit** [comment]
> @mernit Glad to contribute.
> 
> BTW Pages end with `</html></body></html>`

I don't see that, can you share an example?

**Comment by szepeviktor** [comment]
view-source:https://docs.beam.cloud/v2/getting-started/quickstart
or number 61. on
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.beam.cloud%2Fv2%2Fgetting-started%2Fquickstart
