### ISSUE TITLE
Model not being moved to GPU

### ISSUE THREAD

**Issue by dhanushreddy291** [slai-labs/get-beam#45]
In this replit-code, I feel the model is not being moved to GPU:
https://github.com/slai-labs/get-beam/blob/main/examples/replit-code/replit-code.py

Also the cache_dir is not being used in the instantiation of `AutoModelForCausalLM`

Please correct me if I am wrong

**Comment by NolanTrem** [comment]
Thanks for this catch! Fixed with #46

**Comment by dhanushreddy291** [comment]
Cool 😎
I think cache_dir can also be added to `AutoTokenizer`
