### ISSUE TITLE
Beam not working CentOS

### ISSUE THREAD

**Issue by dougjpsantos1981** [slai-labs/get-beam#91]
Running beam to deploy T5+ : 
(venv) [XXX@gpu-server codeT5+]$ beam deploy app.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib.metadata'
 !  beam-sdk was not found using "python3 -m pip freeze | grep beam-sdk"... Proceeding to install beam-sdk into the environment
Requirement already satisfied: beam-sdk in ./venv/lib/python3.6/site-packages (0.1.0)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/XXX/llm/codeT5+/venv/lib64/python3.6/site-packages/beam/__init__.py", line 24, in <module>
    _config = Config.resolve()
  File "/home/XXX/llm/codeT5+/venv/lib64/python3.6/site-packages/beam/config.py", line 164, in resolve
    raise RuntimeError('Unable to locate config file')
RuntimeError: Unable to locate config file
 !  Invalid app definition.
Usage:
  beam deploy [filename.py:function_name] [flags]

Flags:
  -h, --help             help for deploy
  -p, --profile string   Authenticate with a specific beam profile. (default "default")

(venv) [XXX@gpu-server codeT5+]$ uname -a 
Linux gpu-server 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(venv) [XXX@gpu-server codeT5+]$ python3 --version
Python 3.6.8
(venv) [XXX@gpu-server codeT5+]$  cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by mernit** [comment]
This is caused by Beam getting installed outside the virtualenv you're currently working on. Simple fix:

1. Check which Python env you're working in: `which python` (will print something like `/Users/eli/miniconda3/bin/python`)
2. Install Beam in that env: `[YOUR PYTHON PATH] -m pip install --upgrade beam-sdk`
3. Validate the install by running `beam`
